### ISSUE TITLE
Broken Discord Community Link 

### ISSUE THREAD

**Issue by BarWalter** [pywebagent/pywebagent#2]
Hi, the library looks super interesting and innovative!
Please notice that the community discord link is currently invalid(screenshots attached, tried on both mac and android - both didn't work). 

Would be great if you will be able to fix that, Thank you :)

![AndroidScreenshot-DiscordInvalid](https://github.com/pywebagent/pywebagent/assets/59321157/58e809bb-328c-4ffd-961d-9927a0607031)
<img width="962" alt="MacScreenshot-DiscordInvalid" src="https://github.com/pywebagent/pywebagent/assets/59321157/b31cb087-92c7-45b9-9ffe-dc6b0dcbf023">

**Comment by maximkgn** [comment]
Thanks! 
Fixed.
